"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useAdminAuth } from "./AdminAuthShell";
import { adminMutationError, formatAdminValue, humanizeField, shortId } from "./admin-utils";

type Brand=Record<string,any>;

export default function AdminBrandDetail({id}:{id:string}){
  const {token,api}=useAdminAuth();const [brand,setBrand]=useState<Brand>();const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [form,setForm]=useState({name:"",slug:"",logo_url:""});
  async function load(){setLoading(true);setError("");try{const response=await fetch(`${api}/admin/brands`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(adminMutationError(response.status));const rows=await response.json();const found=Array.isArray(rows)?rows.find(item=>String(item.id)===id):undefined;if(!found)throw new Error("Brand not found.");setBrand(found);setForm({name:String(found.name??""),slug:String(found.slug??""),logo_url:String(found.logo_url??"")})}catch(caught){setError(caught instanceof Error?caught.message:"Brand could not be loaded.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[api,id,token]);
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch(`${api}/admin/brands/${encodeURIComponent(id)}`,{method:"PATCH",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({name:form.name,slug:form.slug,logo_url:form.logo_url||null})});if(!response.ok)throw new Error(adminMutationError(response.status));setEditing(false);await load()}catch(caught){setError(caught instanceof Error?caught.message:"Brand update failed.")}finally{setBusy(false)}}
  if(loading&&!brand)return <p className="admin-empty">Loading brand…</p>;if(!brand)return <><Link className="admin-back" href="/admin/brands">← Back to Brands</Link><p className="admin-alert">{error||"Brand not found."}</p></>;
  return <><Link className="admin-back" href="/admin/brands">← Back to Brands</Link><header className="admin-detail-header"><div><p className="admin-kicker">Brands detail</p><h1>{String(brand.name)}</h1><p className="admin-detail-id">ID {shortId(id)}</p></div><div className="admin-detail-actions"><button type="button" onClick={()=>setEditing(true)}>Edit brand</button></div></header>{error&&<p className="admin-alert" role="alert">{error}</p>}{editing&&<section className="admin-management-form"><header><h2>Edit brand</h2></header><form onSubmit={save}><div className="admin-management-grid"><label>Name<input required maxLength={120} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} value={form.slug} onChange={event=>setForm({...form,slug:event.target.value})}/></label><label className="admin-form-wide">Logo URL<input type="url" maxLength={2048} value={form.logo_url} onChange={event=>setForm({...form,logo_url:event.target.value})}/></label></div><div className="admin-form-actions"><button type="button" onClick={()=>setEditing(false)}>Cancel</button><button className="admin-primary" disabled={busy} type="submit">{busy?"Saving…":"Save"}</button></div></form></section>}<div className="admin-detail-sections"><section className="admin-detail-section"><header><h2>Record</h2></header><dl className="admin-detail-grid">{Object.entries(brand).map(([field,value])=><div className={typeof value==="object"&&value!==null?"admin-detail-wide":""} key={field}><dt>{humanizeField(field)}</dt><dd className={field==="id"||field.endsWith("_id")?"admin-mono":""}>{formatAdminValue(field,value)}</dd></div>)}</dl></section></div></>;
}
