"use client";

import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAdminAuth } from "./AdminAuthShell";
import { adminMutationError } from "./admin-utils";

type Brand={id:string;name:string;slug:string;logo_url?:string|null;created_at?:string;updated_at?:string};

export default function AdminBrandsPageClient(){
  const {token,api}=useAdminAuth();const router=useRouter();const [brands,setBrands]=useState<Brand[]>([]);const [filter,setFilter]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [showAdd,setShowAdd]=useState(false);const [busy,setBusy]=useState(false);const [form,setForm]=useState({name:"",slug:"",logo_url:""});
  async function load(){setLoading(true);setError("");try{const response=await fetch(`${api}/admin/brands`,{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(adminMutationError(response.status));setBrands(await response.json())}catch(caught){setError(caught instanceof Error?caught.message:"Brands could not be loaded.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[api,token]);
  const rows=useMemo(()=>{const term=filter.trim().toLowerCase();return term?brands.filter(brand=>JSON.stringify(brand).toLowerCase().includes(term)):brands},[brands,filter]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch(`${api}/admin/brands`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({name:form.name,slug:form.slug,logo_url:form.logo_url||null})});if(!response.ok)throw new Error(adminMutationError(response.status));const created=await response.json();setShowAdd(false);setForm({name:"",slug:"",logo_url:""});await load();router.push(`/admin/brands/${encodeURIComponent(String(created.id))}`)}catch(caught){setError(caught instanceof Error?caught.message:"Brand creation failed.")}finally{setBusy(false)}}
  return <><header className="admin-page-header"><div><p className="admin-kicker">Operations</p><h1>Brands</h1><p>Fuel station brands used to identify station networks.</p></div><div className="admin-page-actions"><button className="admin-primary" type="button" style={{width:"auto",marginTop:0}} onClick={()=>setShowAdd(current=>!current)}>{showAdd?"Cancel":"Add brand"}</button><span className="admin-count">{rows.length} records</span></div></header>{error&&<p className="admin-alert" role="alert">{error}</p>}{showAdd&&<section className="admin-management-form"><header><h2>Add brand</h2></header><form onSubmit={submit}><div className="admin-management-grid"><label>Name<input required maxLength={120} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} value={form.slug} onChange={event=>setForm({...form,slug:event.target.value})}/></label><label className="admin-form-wide">Logo URL<input type="url" maxLength={2048} value={form.logo_url} onChange={event=>setForm({...form,logo_url:event.target.value})}/></label></div><div className="admin-form-actions"><button type="button" onClick={()=>setShowAdd(false)}>Cancel</button><button className="admin-primary" disabled={busy} type="submit">{busy?"Saving…":"Save"}</button></div></form></section>}<div className="admin-list-card"><div className="admin-list-toolbar"><input aria-label="Filter brands" placeholder="Search all fields…" type="search" value={filter} onChange={event=>setFilter(event.target.value)}/></div>{loading?<p className="admin-empty">Loading…</p>:rows.length===0?<p className="admin-empty">No records found.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Logo URL</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map(brand=>{const href=`/admin/brands/${encodeURIComponent(brand.id)}`;return <tr key={brand.id} role="link" tabIndex={0} onClick={()=>router.push(href)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")router.push(href)}}><td>{brand.name}</td><td>{brand.slug}</td><td>{brand.logo_url||"—"}</td><td className="admin-row-arrow">→</td></tr>})}</tbody></table></div>}</div></>;
}
