import uuid
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import select
from app.models import Observation, RateLimit, Station, Verification
from app.routes import enforce_expensive_limit
def test_auth_required(client):assert client.get("/api/v1/me").status_code==401
def test_vehicle_crud_and_ownership(client,user_headers):
    data={"nickname":"RAV4","make":"Toyota","model":"RAV4","fuel_type":"PETROL_91"};created=client.post("/api/v1/vehicles",json=data,headers=user_headers);assert created.status_code==201;vehicle=created.json();assert vehicle["is_primary"]
    other={"Authorization":f"Bearer dev:{uuid.uuid4()}"};assert client.get(f"/api/v1/vehicles/{vehicle['id']}",headers=other).status_code==404
    assert client.patch(f"/api/v1/vehicles/{vehicle['id']}",json={"nickname":"Family car"},headers=user_headers).json()["nickname"]=="Family car"
    assert client.delete(f"/api/v1/vehicles/{vehicle['id']}",headers=user_headers).status_code==204
def test_admin_restricted(client,user_headers):assert client.get("/api/v1/admin/dashboard",headers=user_headers).status_code==403
def test_upload_intent_is_bound_and_single_use(client,user_headers):
    prepared=client.post("/api/v1/media/upload-url",json={"type":"RECEIPT","mime_type":"image/jpeg","file_size":100},headers=user_headers).json()
    wrong=client.post("/api/v1/media/complete",json={"storage_token":prepared["storage_token"],"type":"ODOMETER","mime_type":"image/jpeg","file_size":100},headers=user_headers);assert wrong.status_code==422
    body={"storage_token":prepared["storage_token"],"type":"RECEIPT","mime_type":"image/jpeg","file_size":100};assert client.post("/api/v1/media/complete",json=body,headers=user_headers).status_code==201;assert client.post("/api/v1/media/complete",json=body,headers=user_headers).status_code==409
def test_media_metadata_is_owned(client,user_headers):
    prepared=client.post("/api/v1/media/upload-url",json={"type":"ODOMETER","mime_type":"image/jpeg","file_size":100},headers=user_headers).json();media=client.post("/api/v1/media/complete",json={"storage_token":prepared["storage_token"],"type":"ODOMETER","mime_type":"image/jpeg","file_size":100},headers=user_headers).json()
    assert client.get(f"/api/v1/media/{media['id']}",headers=user_headers).json()["type"]=="ODOMETER"
    assert client.get(f"/api/v1/media/{media['id']}",headers={"Authorization":f"Bearer dev:{uuid.uuid4()}"}).status_code==404
def test_development_limiter_enforces_bound(db):
    user=uuid.uuid4();enforce_expensive_limit(db,user,"test",2);enforce_expensive_limit(db,user,"test",2)
    try:enforce_expensive_limit(db,user,"test",2)
    except Exception as exc:assert getattr(exc,"status_code",None)==429
    else:raise AssertionError("rate limit was not enforced")
    assert db.scalar(select(RateLimit).where(RateLimit.key==f"test:{user}")) is not None
def test_receipt_cannot_verify_modified_fillup(client,user_headers,db):
    station=Station(name="Test Station",address_line="1 Test Street",city="Christchurch",latitude=Decimal("-43.5"),longitude=Decimal("172.6"));db.add(station);db.commit();vehicle=client.post("/api/v1/vehicles",json={"nickname":"Car","make":"Test","model":"One","fuel_type":"PETROL_91"},headers=user_headers).json();prepared=client.post("/api/v1/media/upload-url",json={"type":"RECEIPT","mime_type":"image/jpeg","file_size":100},headers=user_headers).json();media=client.post("/api/v1/media/complete",json={"storage_token":prepared["storage_token"],"type":"RECEIPT","mime_type":"image/jpeg","file_size":100},headers=user_headers).json();receipt=client.post("/api/v1/receipts",json={"media_asset_id":media["id"]},headers=user_headers).json();client.post(f"/api/v1/receipts/{receipt['id']}/process",headers=user_headers);when=datetime.now(timezone.utc).isoformat();client.post(f"/api/v1/receipts/{receipt['id']}/confirm",json={"station_id":str(station.id),"fuel_type":"PETROL_91","litres":"42.3","pump_price_per_litre":"2.239","total_amount":"94.71","transaction_datetime":when},headers=user_headers)
    created=client.post("/api/v1/fill-ups",json={"vehicle_id":vehicle["id"],"station_id":str(station.id),"occurred_at":when,"fuel_type":"PETROL_91","litres":"42.3","pump_price_per_litre":"3.999","total_amount":"94.71","odometer_km":80000,"receipt_id":receipt["id"]},headers=user_headers);assert created.status_code==201
    observation=db.scalar(select(Observation));db.refresh(observation);assert observation.verification_level==Verification.USER_CONFIRMED;assert observation.receipt_id is None
def test_verified_receipt_fillup_is_idempotent(client,user_headers,db):
    station=Station(name="Verified",address_line="1 Fuel Road",city="Auckland",latitude=Decimal("-36.85"),longitude=Decimal("174.76"));db.add(station);db.commit();vehicle=client.post("/api/v1/vehicles",json={"nickname":"Car","make":"Test","model":"One","fuel_type":"PETROL_91"},headers=user_headers).json();prepared=client.post("/api/v1/media/upload-url",json={"type":"RECEIPT","mime_type":"image/jpeg","file_size":100},headers=user_headers).json();media=client.post("/api/v1/media/complete",json={"storage_token":prepared["storage_token"],"type":"RECEIPT","mime_type":"image/jpeg","file_size":100},headers=user_headers).json();receipt=client.post("/api/v1/receipts",json={"media_asset_id":media["id"]},headers=user_headers).json();client.post(f"/api/v1/receipts/{receipt['id']}/process",headers=user_headers);when=datetime.now(timezone.utc).isoformat();confirmed={"station_id":str(station.id),"fuel_type":"PETROL_91","litres":"40","pump_price_per_litre":"2.2","total_amount":"88","transaction_datetime":when};assert client.post(f"/api/v1/receipts/{receipt['id']}/confirm",json=confirmed,headers=user_headers).status_code==200
    payload={"vehicle_id":vehicle["id"],"station_id":str(station.id),"occurred_at":when,"fuel_type":"PETROL_91","litres":"40","pump_price_per_litre":"2.2","total_amount":"88","odometer_km":80000,"receipt_id":receipt["id"]};first=client.post("/api/v1/fill-ups",json=payload,headers=user_headers);second=client.post("/api/v1/fill-ups",json=payload,headers=user_headers);assert first.status_code==201;assert second.json()["id"]==first.json()["id"]
    observation=db.scalar(select(Observation));db.refresh(observation);assert observation.verification_level==Verification.VERIFIED_RECEIPT
    other={"Authorization":f"Bearer dev:{uuid.uuid4()}"};public=client.get("/api/v1/fuel-prices/nearby?latitude=-36.85&longitude=174.76&radius_km=5&fuel_type=PETROL_91",headers=other);assert public.status_code==200;assert public.json()[0]["verification_level"]=="VERIFIED_RECEIPT";assert "receipt_id" not in public.text and "user_id" not in public.text
def test_nearby_and_admin_endpoints_are_privacy_scoped(client,user_headers,db):
    station=Station(name="Public Test",address_line="2 Test Street",city="Christchurch",latitude=Decimal("-43.5"),longitude=Decimal("172.6"));db.add(station);db.commit();response=client.get("/api/v1/fuel-stations/nearby?latitude=-43.5&longitude=172.6",headers=user_headers);assert response.status_code==200;assert response.json()[0]["station"]["name"]=="Public Test";assert "user_id" not in response.text
    admin={"Authorization":user_headers["Authorization"]+":admin"};assert client.get("/api/v1/admin/users",headers=admin).status_code==200;assert client.patch(f"/api/v1/admin/stations/{station.id}?name=Renamed",headers=admin).json()["name"]=="Renamed"
def test_fillup_reference_and_timestamp_validation(client,user_headers):
    vehicle=client.post("/api/v1/vehicles",json={"nickname":"Car","make":"Test","model":"One","fuel_type":"PETROL_91"},headers=user_headers).json();payload={"vehicle_id":vehicle["id"],"occurred_at":"2026-01-01T12:00:00","fuel_type":"PETROL_91","litres":"40","total_amount":"90","odometer_km":100};assert client.post("/api/v1/fill-ups",json=payload,headers=user_headers).status_code==422;payload["occurred_at"]=datetime.now(timezone.utc).isoformat();payload["station_id"]=str(uuid.uuid4());assert client.post("/api/v1/fill-ups",json=payload,headers=user_headers).status_code==422
def test_fillup_crud_and_ownership(client,user_headers):
    vehicle=client.post("/api/v1/vehicles",json={"nickname":"CRUD","make":"Test","model":"Car","fuel_type":"DIESEL"},headers=user_headers).json();payload={"vehicle_id":vehicle["id"],"occurred_at":datetime.now(timezone.utc).isoformat(),"fuel_type":"DIESEL","litres":"50","pump_price_per_litre":"2","total_amount":"100","odometer_km":5000};created=client.post("/api/v1/fill-ups",json=payload,headers=user_headers);assert created.status_code==201;item=created.json();assert client.get(f"/api/v1/fill-ups/{item['id']}",headers=user_headers).status_code==200;assert len(client.get(f"/api/v1/fill-ups?vehicle_id={vehicle['id']}",headers=user_headers).json())==1
    other={"Authorization":f"Bearer dev:{uuid.uuid4()}"};assert client.get(f"/api/v1/fill-ups/{item['id']}",headers=other).status_code==404;updated=client.patch(f"/api/v1/fill-ups/{item['id']}",json={"notes":"edited","total_amount":"105"},headers=user_headers);assert updated.json()["notes"]=="edited";assert client.delete(f"/api/v1/fill-ups/{item['id']}",headers=user_headers).status_code==204;assert client.get(f"/api/v1/fill-ups/{item['id']}",headers=user_headers).status_code==404
