import enum, uuid
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import Boolean, CheckConstraint, DateTime, Enum, ForeignKey, ForeignKeyConstraint, Index, JSON, Numeric, String, Text, UniqueConstraint, text
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base

def now(): return datetime.now(timezone.utc)
class FuelType(str, enum.Enum): PETROL_91="PETROL_91"; PETROL_95="PETROL_95"; PETROL_98="PETROL_98"; DIESEL="DIESEL"; OTHER="OTHER"
class Status(str, enum.Enum): UPLOADED="UPLOADED"; PROCESSING="PROCESSING"; REVIEW_REQUIRED="REVIEW_REQUIRED"; READY="READY"; FAILED="FAILED"; CONFIRMED="CONFIRMED"
class MediaType(str, enum.Enum): RECEIPT="RECEIPT"; ODOMETER="ODOMETER"; OTHER="OTHER"
class Source(str, enum.Enum): RECEIPT="RECEIPT"; COMMUNITY="COMMUNITY"; ADMIN="ADMIN"; EXTERNAL="EXTERNAL"
class Verification(str, enum.Enum): VERIFIED_RECEIPT="VERIFIED_RECEIPT"; USER_CONFIRMED="USER_CONFIRMED"; UNVERIFIED="UNVERIFIED"
class OCRJobKind(str, enum.Enum): RECEIPT="RECEIPT"; ODOMETER="ODOMETER"; PRICE_BOARD="PRICE_BOARD"
class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=now, onupdate=now)
class Profile(Base, TimestampMixin):
    __tablename__="profiles"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); auth_user_id: Mapped[str]=mapped_column(String, unique=True); display_name: Mapped[str|None]=mapped_column(String); country_code: Mapped[str]=mapped_column(String(2), default="NZ"); preferred_currency: Mapped[str]=mapped_column(String(3), default="NZD"); preferred_distance_unit: Mapped[str]=mapped_column(String, default="km"); preferred_efficiency_unit: Mapped[str]=mapped_column(String, default="L_PER_100KM"); deleted_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Vehicle(Base, TimestampMixin):
    __tablename__="vehicles"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id", ondelete="CASCADE"), index=True); nickname: Mapped[str]=mapped_column(String); make: Mapped[str]=mapped_column(String); model: Mapped[str]=mapped_column(String); year: Mapped[int|None]; variant: Mapped[str|None]=mapped_column(String); fuel_type: Mapped[FuelType]=mapped_column(Enum(FuelType)); registration_plate: Mapped[str|None]=mapped_column(String); tank_capacity_litres: Mapped[Decimal|None]=mapped_column(Numeric(8,3)); is_primary: Mapped[bool]=mapped_column(Boolean, default=False); is_archived: Mapped[bool]=mapped_column(Boolean, default=False); __table_args__=(Index("uq_vehicle_primary_user", "user_id",unique=True,postgresql_where=text("is_primary = true and is_archived = false"),sqlite_where=text("is_primary = 1 and is_archived = 0")),CheckConstraint("tank_capacity_litres is null or tank_capacity_litres > 0",name="vehicle_tank_positive"),UniqueConstraint("id","user_id",name="uq_vehicle_owner"))
class Brand(Base, TimestampMixin):
    __tablename__="fuel_station_brands"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); name: Mapped[str]=mapped_column(String); slug: Mapped[str]=mapped_column(String, unique=True); logo_url: Mapped[str|None]=mapped_column(String)
class Station(Base, TimestampMixin):
    __tablename__="fuel_stations"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); brand_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("fuel_station_brands.id"), index=True); name: Mapped[str]=mapped_column(String); google_place_id: Mapped[str|None]=mapped_column(String, unique=True); address_line: Mapped[str]=mapped_column(String); suburb: Mapped[str|None]=mapped_column(String); city: Mapped[str]=mapped_column(String, index=True); region: Mapped[str|None]=mapped_column(String); postal_code: Mapped[str|None]=mapped_column(String); country_code: Mapped[str]=mapped_column(String(2), default="NZ"); latitude: Mapped[Decimal]=mapped_column(Numeric(9,6)); longitude: Mapped[Decimal]=mapped_column(Numeric(9,6)); timezone: Mapped[str]=mapped_column(String, default="Pacific/Auckland"); is_active: Mapped[bool]=mapped_column(Boolean, default=True)
    __table_args__=(Index("ix_station_location","latitude","longitude"),CheckConstraint("latitude between -90 and 90",name="station_latitude_range"),CheckConstraint("longitude between -180 and 180",name="station_longitude_range"))
class MediaAsset(Base):
    __tablename__="media_assets"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id", ondelete="CASCADE"), index=True); type: Mapped[MediaType]=mapped_column(Enum(MediaType)); storage_bucket: Mapped[str]=mapped_column(String, default="private-media"); storage_path: Mapped[str]=mapped_column(String, unique=True); mime_type: Mapped[str]=mapped_column(String); file_size: Mapped[int]; width: Mapped[int|None]; height: Mapped[int|None]; content_sha256: Mapped[str|None]=mapped_column(String(64)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now); deleted_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));__table_args__=(CheckConstraint("file_size > 0",name="media_size_positive"),CheckConstraint("width is null or width > 0",name="media_width_positive"),CheckConstraint("height is null or height > 0",name="media_height_positive"),UniqueConstraint("id","user_id",name="uq_media_owner"),Index("uq_receipt_media_content","content_sha256",unique=True,postgresql_where=text("type = 'RECEIPT'"),sqlite_where=text("type = 'RECEIPT'")))
class Receipt(Base):
    __tablename__="receipts"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id", ondelete="CASCADE"), index=True); media_asset_id: Mapped[uuid.UUID]=mapped_column(unique=True); station_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("fuel_stations.id")); processing_status: Mapped[Status]=mapped_column(Enum(Status), default=Status.UPLOADED); ocr_provider: Mapped[str|None]=mapped_column(String); raw_result_json: Mapped[dict|None]=mapped_column(JSON); station_text: Mapped[str|None]=mapped_column(String); station_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); fuel_type: Mapped[FuelType|None]=mapped_column(Enum(FuelType)); fuel_type_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); litres: Mapped[Decimal|None]=mapped_column(Numeric(10,3)); litres_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); pump_price_per_litre: Mapped[Decimal|None]=mapped_column(Numeric(8,4)); price_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); discount_amount: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); discount_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); total_amount: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); total_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); transaction_datetime: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); datetime_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); overall_confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); error_code: Mapped[str|None]=mapped_column(String); error_message: Mapped[str|None]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now); processed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));__table_args__=(CheckConstraint("litres is null or litres > 0",name="receipt_litres_positive"),CheckConstraint("pump_price_per_litre is null or pump_price_per_litre > 0",name="receipt_price_positive"),CheckConstraint("total_amount is null or total_amount > 0",name="receipt_total_positive"),CheckConstraint("discount_amount is null or discount_amount >= 0",name="receipt_discount_nonnegative"),UniqueConstraint("id","user_id",name="uq_receipt_owner"),ForeignKeyConstraint(["media_asset_id","user_id"],["media_assets.id","media_assets.user_id"],name="fk_receipt_media_owner"),*[CheckConstraint(f"{field} is null or {field} between 0 and 1",name=f"receipt_{field}_range") for field in ("station_confidence","fuel_type_confidence","litres_confidence","price_confidence","discount_confidence","total_confidence","datetime_confidence","overall_confidence")])
class UploadIntent(Base):
    __tablename__="upload_intents"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4);user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id",ondelete="CASCADE"),index=True);type: Mapped[MediaType]=mapped_column(Enum(MediaType));storage_path: Mapped[str]=mapped_column(String,unique=True);mime_type: Mapped[str]=mapped_column(String);file_size: Mapped[int];expires_at: Mapped[datetime]=mapped_column(DateTime(timezone=True));completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);__table_args__=(CheckConstraint("file_size > 0",name="upload_size_positive"),)
class RateLimit(Base):
    __tablename__="rate_limits";key:Mapped[str]=mapped_column(String,primary_key=True);window_started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));count:Mapped[int]=mapped_column(default=0)
class ReceiptFingerprint(Base):
    __tablename__="receipt_fingerprints";content_sha256:Mapped[str]=mapped_column(String(64),primary_key=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AccountDeletion(Base):
    __tablename__="account_deletions";id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4);user_id:Mapped[uuid.UUID]=mapped_column(unique=True);status:Mapped[str]=mapped_column(String,default="REQUESTED");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now);__table_args__=(CheckConstraint("status in ('REQUESTED','STORAGE_DELETED','COMPLETED')",name="deletion_status_valid"),)
class OdometerReading(Base):
    __tablename__="odometer_readings"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id", ondelete="CASCADE"), index=True); vehicle_id: Mapped[uuid.UUID]; media_asset_id: Mapped[uuid.UUID]; reading_km: Mapped[int|None]; confidence: Mapped[Decimal|None]=mapped_column(Numeric(4,3)); processing_status: Mapped[Status]=mapped_column(Enum(Status), default=Status.UPLOADED); raw_result_json: Mapped[dict|None]=mapped_column(JSON);error_code:Mapped[str|None]=mapped_column(String);error_message:Mapped[str|None]=mapped_column(String); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now); processed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));__table_args__=(CheckConstraint("reading_km is null or reading_km >= 0",name="odometer_nonnegative"),CheckConstraint("confidence is null or confidence between 0 and 1",name="odometer_confidence_range"),ForeignKeyConstraint(["vehicle_id","user_id"],["vehicles.id","vehicles.user_id"],name="fk_odometer_vehicle_owner"),ForeignKeyConstraint(["media_asset_id","user_id"],["media_assets.id","media_assets.user_id"],name="fk_odometer_media_owner"))
class OCRJob(Base):
    claim_token:Mapped[uuid.UUID|None]=mapped_column()
    __tablename__="ocr_jobs";id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4);user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id",ondelete="CASCADE"),index=True);kind:Mapped[OCRJobKind]=mapped_column(Enum(OCRJobKind));resource_id:Mapped[uuid.UUID]=mapped_column(index=True);station_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("fuel_stations.id"));media_asset_id:Mapped[uuid.UUID];status:Mapped[Status]=mapped_column(Enum(Status),default=Status.UPLOADED,index=True);result_json:Mapped[dict|None]=mapped_column(JSON);confidence:Mapped[Decimal|None]=mapped_column(Numeric(4,3));requires_confirmation:Mapped[bool]=mapped_column(Boolean,default=True);applied_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));error_message:Mapped[str|None]=mapped_column(String);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));__table_args__=(CheckConstraint("confidence is null or confidence between 0 and 1",name="ocr_job_confidence_range"),ForeignKeyConstraint(["media_asset_id","user_id"],["media_assets.id","media_assets.user_id"],ondelete="CASCADE",name="fk_ocr_job_media_owner"),Index("ix_ocr_jobs_owner_created","user_id","created_at"),Index("uq_ocr_job_active_resource","user_id","kind","resource_id",unique=True,postgresql_where=text("status in ('UPLOADED','PROCESSING')"),sqlite_where=text("status in ('UPLOADED','PROCESSING')")))
class FillUp(Base, TimestampMixin):
    __tablename__="fill_ups"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); user_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("profiles.id", ondelete="CASCADE"), index=True); vehicle_id: Mapped[uuid.UUID]=mapped_column(index=True); station_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("fuel_stations.id")); occurred_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); fuel_type: Mapped[FuelType]=mapped_column(Enum(FuelType)); litres: Mapped[Decimal]=mapped_column(Numeric(10,3)); pump_price_per_litre: Mapped[Decimal|None]=mapped_column(Numeric(8,4)); paid_price_per_litre: Mapped[Decimal|None]=mapped_column(Numeric(8,4)); subtotal: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); discount_amount: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); total_amount: Mapped[Decimal]=mapped_column(Numeric(12,2)); currency: Mapped[str]=mapped_column(String(3), default="NZD"); odometer_km: Mapped[int]; full_tank: Mapped[bool]=mapped_column(Boolean, default=True); missed_previous_fill: Mapped[bool]=mapped_column(Boolean, default=False); notes: Mapped[str|None]=mapped_column(Text); receipt_id: Mapped[uuid.UUID|None]=mapped_column(unique=True); odometer_image_id: Mapped[uuid.UUID|None]; distance_since_previous_km: Mapped[int|None]; fuel_economy_l_per_100km: Mapped[Decimal|None]=mapped_column(Numeric(8,3)); cost_per_100km: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); economy_fuel_litres: Mapped[Decimal|None]=mapped_column(Numeric(12,3)); economy_cost_amount: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); economy_started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));economy_is_valid: Mapped[bool]=mapped_column(Boolean,default=False); economy_warning: Mapped[str|None]=mapped_column(String); __table_args__=(CheckConstraint("litres > 0",name="fill_up_litres_positive"),CheckConstraint("total_amount > 0",name="fill_up_total_positive"),CheckConstraint("odometer_km >= 0",name="fill_up_odometer_nonnegative"),CheckConstraint("pump_price_per_litre is null or pump_price_per_litre > 0",name="fill_up_price_positive"),UniqueConstraint("vehicle_id","occurred_at",name="uq_fill_vehicle_occurred"),ForeignKeyConstraint(["vehicle_id","user_id"],["vehicles.id","vehicles.user_id"],name="fk_fill_vehicle_owner"),ForeignKeyConstraint(["receipt_id","user_id"],["receipts.id","receipts.user_id"],name="fk_fill_receipt_owner"),ForeignKeyConstraint(["odometer_image_id","user_id"],["media_assets.id","media_assets.user_id"],name="fk_fill_odometer_media_owner"))
class Observation(Base, TimestampMixin):
    __tablename__="fuel_price_observations"; id: Mapped[uuid.UUID]=mapped_column(primary_key=True, default=uuid.uuid4); station_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("fuel_stations.id"), index=True); fuel_type: Mapped[FuelType]=mapped_column(Enum(FuelType)); pump_price_per_litre: Mapped[Decimal|None]=mapped_column(Numeric(8,4)); paid_price_per_litre: Mapped[Decimal|None]=mapped_column(Numeric(8,4)); discount_per_litre: Mapped[Decimal|None]=mapped_column(Numeric(8,4)); source: Mapped[Source]=mapped_column(Enum(Source)); verification_level: Mapped[Verification]=mapped_column(Enum(Verification)); observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), index=True); submitted_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now); receipt_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("receipts.id")); fill_up_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("fill_ups.id"), unique=True); media_asset_id: Mapped[uuid.UUID|None]=mapped_column(ForeignKey("media_assets.id",ondelete="SET NULL"), index=True); confidence_score: Mapped[Decimal]=mapped_column(Numeric(4,3)); is_anomaly: Mapped[bool]=mapped_column(Boolean, default=False); is_active: Mapped[bool]=mapped_column(Boolean, default=True); __table_args__=(CheckConstraint("pump_price_per_litre is null or pump_price_per_litre > 0",name="observation_price_positive"),CheckConstraint("confidence_score between 0 and 1",name="observation_confidence_range"),UniqueConstraint("media_asset_id","fuel_type",name="uq_observation_media_fuel"))
class CurrentPrice(Base):
    __tablename__="fuel_station_current_prices"; station_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("fuel_stations.id"), primary_key=True); fuel_type: Mapped[FuelType]=mapped_column(Enum(FuelType), primary_key=True); price: Mapped[Decimal]=mapped_column(Numeric(8,4)); observed_at: Mapped[datetime]=mapped_column(DateTime(timezone=True)); observation_id: Mapped[uuid.UUID]=mapped_column(ForeignKey("fuel_price_observations.id")); confidence_score: Mapped[Decimal]=mapped_column(Numeric(4,3)); verification_level: Mapped[Verification]=mapped_column(Enum(Verification)); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=now);__table_args__=(CheckConstraint("price > 0",name="current_price_positive"),CheckConstraint("confidence_score between 0 and 1",name="current_confidence_range"))
