"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabaseBrowser } from "../../../lib/supabase";

const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api/v1";
type Tier={id?:string;key:string;name:string;threshold:number|null;criteria:any;sort_order:number;icon:string|null};
type Achievement={id:string;key:string;name:string;description:string;category:string;icon:string|null;achievement_type:string;visibility:string;repeatable:boolean;enabled:boolean;sort_order:number;criteria:any;starts_at:string|null;ends_at:string|null;tiers:Tier[]};
type Analytics={contributors:number;achievements:Array<{achievement_id:string;key:string;name:string;category:string;enabled:boolean;earned_users:number;award_count:number;completion_rate:number;rarity:string;average_days_to_unlock:number|null}>};
type UserRow={id:string;display_name?:string|null;auth_user_id?:string};
type Earner={award_id:string;user_id:string;display_name:string|null;tier_id:string|null;period_key:string|null;scope_type:string|null;scope_key:string|null;earned_at:string;revoked_at:string|null;revoke_reason:string|null};

const blank={key:"",name:"",description:"",category:"STARTER",icon:"",achievement_type:"SINGLE",visibility:"PUBLIC",repeatable:false,enabled:true,sort_order:900,criteria:'{"metric":"prices_confirmed","op":"gte","value":1}',tiers:"[]"};

export default function AchievementAdmin(){
  const [token,setToken]=useState(""); const [items,setItems]=useState<Achievement[]>([]); const [analytics,setAnalytics]=useState<Analytics|null>(null); const [users,setUsers]=useState<UserRow[]>([]); const [selected,setSelected]=useState<Achievement|null>(null); const [earners,setEarners]=useState<Earner[]>([]); const [form,setForm]=useState<any>(blank); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [grantUser,setGrantUser]=useState(""); const [grantTier,setGrantTier]=useState(""); const [grantNote,setGrantNote]=useState("");
  const headers=useMemo(()=>({authorization:`Bearer ${token}`,"content-type":"application/json"}),[token]);
  useEffect(()=>{let active=true;void supabaseBrowser().auth.getSession().then(({data})=>{if(active)setToken(data.session?.access_token||"")});return()=>{active=false}},[]);
  useEffect(()=>{if(!token){setLoading(false);return}void loadAll()},[token]);
  async function request(path:string,init?:RequestInit){const response=await fetch(`${api}${path}`,{...init,headers:{...headers,...(init?.headers||{})}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||body?.detail||"Request failed");return body}
  async function loadAll(){setLoading(true);setError("");try{const [defs,stats,userRows]=await Promise.all([request("/admin/achievements"),request("/admin/achievements/analytics/summary"),request("/admin/users")]);setItems(defs);setAnalytics(stats);setUsers(Array.isArray(userRows)?userRows:[])}catch(e){setError(e instanceof Error?e.message:"Could not load achievement operations.")}finally{setLoading(false)}}
  function select(item:Achievement){setSelected(item);setForm({key:item.key,name:item.name,description:item.description,category:item.category,icon:item.icon||"",achievement_type:item.achievement_type,visibility:item.visibility,repeatable:item.repeatable,enabled:item.enabled,sort_order:item.sort_order,criteria:JSON.stringify(item.criteria,null,2),tiers:JSON.stringify(item.tiers.map(({id,...tier})=>tier),null,2)});setGrantTier(item.tiers[0]?.id||"");setMessage("");setError("");void loadEarners(item.id)}
  async function loadEarners(id:string){try{setEarners(await request(`/admin/achievements/${id}/earners`))}catch{setEarners([])}}
  function reset(){setSelected(null);setForm(blank);setEarners([]);setGrantUser("");setGrantTier("");setGrantNote("")}
  async function save(event:FormEvent){event.preventDefault();setMessage("");setError("");try{const criteria=JSON.parse(form.criteria||"{}");const tiers=JSON.parse(form.tiers||"[]");if(selected){await request(`/admin/achievements/${selected.id}`,{method:"PATCH",body:JSON.stringify({name:form.name,description:form.description,category:form.category,icon:form.icon||null,visibility:form.visibility,enabled:form.enabled,sort_order:Number(form.sort_order),criteria})});if(selected.achievement_type==="TIERED")await request(`/admin/achievements/${selected.id}/tiers`,{method:"PUT",body:JSON.stringify({tiers})});setMessage("Achievement updated.")}else{await request("/admin/achievements",{method:"POST",body:JSON.stringify({key:form.key,name:form.name,description:form.description,category:form.category,icon:form.icon||null,achievement_type:form.achievement_type,visibility:form.visibility,repeatable:form.repeatable,enabled:form.enabled,sort_order:Number(form.sort_order),criteria,tiers})});setMessage("Achievement created.")}await loadAll();reset()}catch(e){setError(e instanceof Error?e.message:"Could not save achievement.")}}
  async function grant(){if(!selected||!grantUser)return;setError("");setMessage("");try{await request(`/admin/achievements/${selected.id}/grant`,{method:"POST",body:JSON.stringify({user_id:grantUser,tier_id:selected.achievement_type==="TIERED"?grantTier||null:null,note:grantNote||null})});setMessage("Achievement granted.");await Promise.all([loadEarners(selected.id),loadAll()])}catch(e){setError(e instanceof Error?e.message:"Could not grant achievement.")}}
  async function revoke(earner:Earner){if(!selected)return;const reason=window.prompt("Reason for revoking this user's achievement?");if(!reason)return;try{await request(`/admin/users/${earner.user_id}/achievements/${selected.id}/revoke`,{method:"POST",body:JSON.stringify({reason})});setMessage("Achievement revoked.");await Promise.all([loadEarners(selected.id),loadAll()])}catch(e){setError(e instanceof Error?e.message:"Could not revoke achievement.")}}
  const statById=Object.fromEntries((analytics?.achievements||[]).map(row=>[row.achievement_id,row]));
  if(!token&&!loading)return <main className="wrap page-shell"><p className="location-message">Sign in with an admin account to manage achievements.</p></main>;
  return <main className="admin-achievement-page">
    <header className="admin-achievement-top"><div><p className="admin-kicker">Operations</p><h1>Achievements</h1><p>Create, tune, grant and measure Autoroa badges without a code deployment.</p></div><div><Link href="/admin">← Admin</Link><button className="admin-primary" onClick={reset}>New achievement</button></div></header>
    {error&&<p className="admin-alert" role="alert">{error}</p>}{message&&<p className="admin-success" role="status">{message}</p>}
    <section className="admin-achievement-stats"><article><strong>{analytics?.contributors??"—"}</strong><span>contributors</span></article><article><strong>{items.length}</strong><span>definitions</span></article><article><strong>{analytics?.achievements.filter(a=>a.rarity==="Legendary").length??0}</strong><span>legendary</span></article></section>
    <div className="admin-achievement-layout">
      <section className="admin-achievement-list"><header><h2>Badge catalogue</h2><span>{items.length}</span></header>{loading?<p>Loading…</p>:items.map(item=>{const stat=statById[item.id];return <button key={item.id} className={selected?.id===item.id?"active":""} onClick={()=>select(item)}><span><strong>{item.name}</strong><small>{item.category} · {item.achievement_type}</small></span><span><b>{stat?.completion_rate??0}%</b><small>{stat?.rarity||"—"}</small></span></button>})}</section>
      <section className="admin-achievement-editor"><form onSubmit={save}><header><div><p className="admin-kicker">{selected?"Edit definition":"New definition"}</p><h2>{selected?.name||"Create achievement"}</h2></div>{selected&&<span className={`achievement-rarity rarity-${String(statById[selected.id]?.rarity||"").toLowerCase()}`}>{statById[selected.id]?.rarity}</span>}</header><div className="admin-achievement-form-grid">
        <label>Key<input disabled={!!selected} required value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value.toUpperCase()})}/></label><label>Icon<input value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label>Type<select disabled={!!selected} value={form.achievement_type} onChange={e=>setForm({...form,achievement_type:e.target.value})}><option>SINGLE</option><option>TIERED</option><option>REPEATABLE</option><option>STATUS</option></select></label><label>Visibility<select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option>PUBLIC</option><option>HIDDEN</option><option>SECRET</option></select></label><label>Sort order<input type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="admin-checkbox"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enabled</label><label className="admin-checkbox"><input disabled={!!selected} type="checkbox" checked={form.repeatable} onChange={e=>setForm({...form,repeatable:e.target.checked})}/>Repeatable</label><label className="wide">Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Criteria JSON<textarea className="admin-code-textarea" required value={form.criteria} onChange={e=>setForm({...form,criteria:e.target.value})}/></label>{form.achievement_type==="TIERED"&&<label className="wide">Tiers JSON<textarea className="admin-code-textarea" required value={form.tiers} onChange={e=>setForm({...form,tiers:e.target.value})}/></label>}
      </div><div className="admin-form-actions"><button type="button" onClick={reset}>Clear</button><button className="admin-primary" type="submit">{selected?"Save changes":"Create achievement"}</button></div></form>
      {selected&&<><section className="admin-achievement-analytics"><h3>Performance</h3><div>{[["Earned users",statById[selected.id]?.earned_users??0],["Awards",statById[selected.id]?.award_count??0],["Completion",`${statById[selected.id]?.completion_rate??0}%`],["Avg. unlock",statById[selected.id]?.average_days_to_unlock==null?"—":`${statById[selected.id]?.average_days_to_unlock} days`]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div></section><section className="admin-achievement-grant"><h3>Grant manually</h3><div><label>User<select value={grantUser} onChange={e=>setGrantUser(e.target.value)}><option value="">Choose user</option>{users.map(user=><option key={user.id} value={user.id}>{user.display_name||user.auth_user_id||user.id}</option>)}</select></label>{selected.achievement_type==="TIERED"&&<label>Tier<select value={grantTier} onChange={e=>setGrantTier(e.target.value)}>{selected.tiers.map(tier=><option key={tier.id} value={tier.id}>{tier.name}</option>)}</select></label>}<label>Note<input value={grantNote} onChange={e=>setGrantNote(e.target.value)}/></label><button className="admin-primary" type="button" onClick={()=>void grant()} disabled={!grantUser}>Grant</button></div></section><section className="admin-achievement-earners"><h3>Recent earners</h3>{earners.length===0?<p>No awards yet.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Earned</th><th>Scope</th><th>Status</th><th></th></tr></thead><tbody>{earners.map(row=><tr key={row.award_id}><td>{row.display_name||row.user_id}</td><td>{new Date(row.earned_at).toLocaleDateString("en-NZ")}</td><td>{[row.period_key,row.scope_key].filter(Boolean).join(" · ")||"—"}</td><td>{row.revoked_at?"Revoked":"Active"}</td><td>{!row.revoked_at&&<button type="button" onClick={()=>void revoke(row)}>Revoke</button>}</td></tr>)}</tbody></table></div>}</section></>}
      </section>
    </div>
  </main>
}
