export type PhotoGps={latitude:number;longitude:number};

function parseGpsFromTiff(bytes:Uint8Array,tiff:number):PhotoGps|undefined{
  const little=bytes[tiff]===0x49&&bytes[tiff+1]===0x49;const big=bytes[tiff]===0x4d&&bytes[tiff+1]===0x4d;if(!little&&!big)return;
  const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);const u16=(offset:number)=>view.getUint16(offset,little);const u32=(offset:number)=>view.getUint32(offset,little);const rational=(offset:number)=>{const denominator=u32(offset+4);return denominator?u32(offset)/denominator:0};
  try{if(u16(tiff+2)!==42)return;const ifd0=tiff+u32(tiff+4);const count=u16(ifd0);let gpsOffset:number|undefined;for(let i=0;i<count;i+=1){const entry=ifd0+2+i*12;if(u16(entry)===0x8825){gpsOffset=tiff+u32(entry+8);break}}if(gpsOffset==null)return;const gpsCount=u16(gpsOffset);let latRef='',lonRef='';let latValues:number[]|undefined,lonValues:number[]|undefined;for(let i=0;i<gpsCount;i+=1){const entry=gpsOffset+2+i*12;const tag=u16(entry),type=u16(entry+2),itemCount=u32(entry+4);if(tag===1&&type===2&&itemCount>=1)latRef=String.fromCharCode(bytes[entry+8]).toUpperCase();if(tag===3&&type===2&&itemCount>=1)lonRef=String.fromCharCode(bytes[entry+8]).toUpperCase();if((tag===2||tag===4)&&type===5&&itemCount===3){const data=tiff+u32(entry+8);const values=[rational(data),rational(data+8),rational(data+16)];if(tag===2)latValues=values;else lonValues=values}}if(!latValues||!lonValues||!/[NS]/.test(latRef)||!/[EW]/.test(lonRef))return;const decimal=([d,m,s]:number[])=>d+m/60+s/3600;const latitude=decimal(latValues)*(latRef==='S'?-1:1),longitude=decimal(lonValues)*(lonRef==='W'?-1:1);if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)return;return{latitude,longitude}}catch{return}
}

export function extractGpsFromImageBytes(buffer:ArrayBuffer):PhotoGps|undefined{const bytes=new Uint8Array(buffer);for(let i=0;i+8<bytes.length;i+=1){const little=bytes[i]===0x49&&bytes[i+1]===0x49&&bytes[i+2]===0x2a&&bytes[i+3]===0;const big=bytes[i]===0x4d&&bytes[i+1]===0x4d&&bytes[i+2]===0&&bytes[i+3]===0x2a;if(little||big){const gps=parseGpsFromTiff(bytes,i);if(gps)return gps}}return}

function writeRational(view:DataView,offset:number,value:number,denominator=1_000_000){view.setUint32(offset,Math.round(value*denominator),true);view.setUint32(offset+4,denominator,true)}
export function gpsExifSegment(gps:PhotoGps){const tiff=new Uint8Array(128);const view=new DataView(tiff.buffer);tiff[0]=0x49;tiff[1]=0x49;view.setUint16(2,42,true);view.setUint32(4,8,true);view.setUint16(8,1,true);view.setUint16(10,0x8825,true);view.setUint16(12,4,true);view.setUint32(14,1,true);view.setUint32(18,26,true);view.setUint32(22,0,true);view.setUint16(26,4,true);const entry=(index:number,tag:number,type:number,count:number,value:number)=>{const offset=28+index*12;view.setUint16(offset,tag,true);view.setUint16(offset+2,type,true);view.setUint32(offset+4,count,true);view.setUint32(offset+8,value,true)};const latRef=gps.latitude<0?'S':'N',lonRef=gps.longitude<0?'W':'E';entry(0,1,2,2,latRef.charCodeAt(0));entry(1,2,5,3,80);entry(2,3,2,2,lonRef.charCodeAt(0));entry(3,4,5,3,104);view.setUint32(76,0,true);const dms=(coordinate:number)=>{const absolute=Math.abs(coordinate),degrees=Math.floor(absolute),minuteValue=(absolute-degrees)*60,minutes=Math.floor(minuteValue);return[degrees,minutes,(minuteValue-minutes)*60]as const};const lat=dms(gps.latitude),lon=dms(gps.longitude);writeRational(view,80,lat[0],1);writeRational(view,88,lat[1],1);writeRational(view,96,lat[2]);writeRational(view,104,lon[0],1);writeRational(view,112,lon[1],1);writeRational(view,120,lon[2]);const payload=new Uint8Array(6+tiff.length);payload.set([0x45,0x78,0x69,0x66,0,0]);payload.set(tiff,6);const segment=new Uint8Array(payload.length+4);segment.set([0xff,0xe1]);const length=payload.length+2;segment[2]=(length>>8)&0xff;segment[3]=length&0xff;segment.set(payload,4);return segment}

export async function injectGpsIntoJpeg(blob:Blob,gps:PhotoGps|undefined){if(!gps)return blob;const bytes=new Uint8Array(await blob.arrayBuffer());if(bytes.length<2||bytes[0]!==0xff||bytes[1]!==0xd8)return blob;return new Blob([bytes.slice(0,2),gpsExifSegment(gps),bytes.slice(2)],{type:'image/jpeg'})}

export async function sniffImageMime(blob:Blob){const bytes=new Uint8Array(await blob.slice(0,32).arrayBuffer());if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return'image/jpeg';if(bytes.length>=8&&bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return'image/png';if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return'image/webp';if(bytes.length>=12&&String.fromCharCode(...bytes.slice(4,8))==='ftyp')return'image/heic';return''}
