"""initial schema

Revision ID: 0001
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('REQUESTED','STORAGE_DELETED','COMPLETED')", name='deletion_status_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fuel_station_brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False),
    sa.Column('preferred_distance_unit', sa.String(), nullable=False),
    sa.Column('preferred_efficiency_unit', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id')
    )
    op.create_table('rate_limits',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('fuel_stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=True),
    sa.Column('address_line', sa.String(), nullable=False),
    sa.Column('suburb', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude between -90 and 90', name='station_latitude_range'),
    sa.CheckConstraint('longitude between -180 and 180', name='station_longitude_range'),
    sa.ForeignKeyConstraint(['brand_id'], ['fuel_station_brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    op.create_index(op.f('ix_fuel_stations_brand_id'), 'fuel_stations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_fuel_stations_city'), 'fuel_stations', ['city'], unique=False)
    op.create_index('ix_station_location', 'fuel_stations', ['latitude', 'longitude'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('RECEIPT', 'ODOMETER', 'OTHER', name='mediatype'), nullable=False),
    sa.Column('storage_bucket', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('file_size > 0', name='media_size_positive'),
    sa.CheckConstraint('height is null or height > 0', name='media_height_positive'),
    sa.CheckConstraint('width is null or width > 0', name='media_width_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_media_assets_user_id'), 'media_assets', ['user_id'], unique=False)
    op.create_table('upload_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('RECEIPT', 'ODOMETER', 'OTHER', name='mediatype'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size > 0', name='upload_size_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_upload_intents_user_id'), 'upload_intents', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.Enum('PETROL_91', 'PETROL_95', 'PETROL_98', 'DIESEL', 'OTHER', name='fueltype'), nullable=False),
    sa.Column('registration_plate', sa.String(), nullable=True),
    sa.Column('tank_capacity_litres', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('tank_capacity_litres is null or tank_capacity_litres > 0', name='vehicle_tank_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_index('uq_vehicle_primary_user', 'vehicles', ['user_id'], unique=True, postgresql_where=sa.text('is_primary = true and is_archived = false'), sqlite_where=sa.text('is_primary = 1 and is_archived = 0'))
    op.create_table('odometer_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('reading_km', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'REVIEW_REQUIRED', 'READY', 'FAILED', 'CONFIRMED', name='status'), nullable=False),
    sa.Column('raw_result_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('confidence is null or confidence between 0 and 1', name='odometer_confidence_range'),
    sa.CheckConstraint('reading_km is null or reading_km >= 0', name='odometer_nonnegative'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odometer_readings_user_id'), 'odometer_readings', ['user_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'REVIEW_REQUIRED', 'READY', 'FAILED', 'CONFIRMED', name='status'), nullable=False),
    sa.Column('ocr_provider', sa.String(), nullable=True),
    sa.Column('raw_result_json', sa.JSON(), nullable=True),
    sa.Column('station_text', sa.String(), nullable=True),
    sa.Column('station_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fuel_type', sa.Enum('PETROL_91', 'PETROL_95', 'PETROL_98', 'DIESEL', 'OTHER', name='fueltype'), nullable=True),
    sa.Column('fuel_type_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('litres', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('litres_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('pump_price_per_litre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('price_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('transaction_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('datetime_confidence is null or datetime_confidence between 0 and 1', name='receipt_datetime_confidence_range'),
    sa.CheckConstraint('discount_amount is null or discount_amount >= 0', name='receipt_discount_nonnegative'),
    sa.CheckConstraint('discount_confidence is null or discount_confidence between 0 and 1', name='receipt_discount_confidence_range'),
    sa.CheckConstraint('fuel_type_confidence is null or fuel_type_confidence between 0 and 1', name='receipt_fuel_type_confidence_range'),
    sa.CheckConstraint('litres is null or litres > 0', name='receipt_litres_positive'),
    sa.CheckConstraint('litres_confidence is null or litres_confidence between 0 and 1', name='receipt_litres_confidence_range'),
    sa.CheckConstraint('overall_confidence is null or overall_confidence between 0 and 1', name='receipt_overall_confidence_range'),
    sa.CheckConstraint('price_confidence is null or price_confidence between 0 and 1', name='receipt_price_confidence_range'),
    sa.CheckConstraint('pump_price_per_litre is null or pump_price_per_litre > 0', name='receipt_price_positive'),
    sa.CheckConstraint('station_confidence is null or station_confidence between 0 and 1', name='receipt_station_confidence_range'),
    sa.CheckConstraint('total_amount is null or total_amount > 0', name='receipt_total_positive'),
    sa.CheckConstraint('total_confidence is null or total_confidence between 0 and 1', name='receipt_total_confidence_range'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_index(op.f('ix_receipts_user_id'), 'receipts', ['user_id'], unique=False)
    op.create_table('fill_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL_91', 'PETROL_95', 'PETROL_98', 'DIESEL', 'OTHER', name='fueltype'), nullable=False),
    sa.Column('litres', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('pump_price_per_litre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('paid_price_per_litre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('full_tank', sa.Boolean(), nullable=False),
    sa.Column('missed_previous_fill', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_id', sa.Uuid(), nullable=True),
    sa.Column('odometer_image_id', sa.Uuid(), nullable=True),
    sa.Column('distance_since_previous_km', sa.Integer(), nullable=True),
    sa.Column('fuel_economy_l_per_100km', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('cost_per_100km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('litres > 0', name='fill_up_litres_positive'),
    sa.CheckConstraint('odometer_km >= 0', name='fill_up_odometer_nonnegative'),
    sa.CheckConstraint('pump_price_per_litre is null or pump_price_per_litre > 0', name='fill_up_price_positive'),
    sa.CheckConstraint('total_amount > 0', name='fill_up_total_positive'),
    sa.ForeignKeyConstraint(['odometer_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    op.create_index(op.f('ix_fill_ups_user_id'), 'fill_ups', ['user_id'], unique=False)
    op.create_index(op.f('ix_fill_ups_vehicle_id'), 'fill_ups', ['vehicle_id'], unique=False)
    op.create_table('fuel_price_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL_91', 'PETROL_95', 'PETROL_98', 'DIESEL', 'OTHER', name='fueltype'), nullable=False),
    sa.Column('pump_price_per_litre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('paid_price_per_litre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('discount_per_litre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.Enum('RECEIPT', 'COMMUNITY', 'ADMIN', 'EXTERNAL', name='source'), nullable=False),
    sa.Column('verification_level', sa.Enum('VERIFIED_RECEIPT', 'USER_CONFIRMED', 'UNVERIFIED', name='verification'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=True),
    sa.Column('fill_up_id', sa.Uuid(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score between 0 and 1', name='observation_confidence_range'),
    sa.CheckConstraint('pump_price_per_litre is null or pump_price_per_litre > 0', name='observation_price_positive'),
    sa.ForeignKeyConstraint(['fill_up_id'], ['fill_ups.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_up_id')
    )
    op.create_index(op.f('ix_fuel_price_observations_observed_at'), 'fuel_price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_fuel_price_observations_station_id'), 'fuel_price_observations', ['station_id'], unique=False)
    op.create_table('fuel_station_current_prices',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL_91', 'PETROL_95', 'PETROL_98', 'DIESEL', 'OTHER', name='fueltype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('verification_level', sa.Enum('VERIFIED_RECEIPT', 'USER_CONFIRMED', 'UNVERIFIED', name='verification'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score between 0 and 1', name='current_confidence_range'),
    sa.CheckConstraint('price > 0', name='current_price_positive'),
    sa.ForeignKeyConstraint(['observation_id'], ['fuel_price_observations.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'fuel_type')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_station_current_prices')
    op.drop_index(op.f('ix_fuel_price_observations_station_id'), table_name='fuel_price_observations')
    op.drop_index(op.f('ix_fuel_price_observations_observed_at'), table_name='fuel_price_observations')
    op.drop_table('fuel_price_observations')
    op.drop_index(op.f('ix_fill_ups_vehicle_id'), table_name='fill_ups')
    op.drop_index(op.f('ix_fill_ups_user_id'), table_name='fill_ups')
    op.drop_table('fill_ups')
    op.drop_index(op.f('ix_receipts_user_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_odometer_readings_user_id'), table_name='odometer_readings')
    op.drop_table('odometer_readings')
    op.drop_index('uq_vehicle_primary_user', table_name='vehicles', postgresql_where=sa.text('is_primary = true and is_archived = false'), sqlite_where=sa.text('is_primary = 1 and is_archived = 0'))
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_upload_intents_user_id'), table_name='upload_intents')
    op.drop_table('upload_intents')
    op.drop_index(op.f('ix_media_assets_user_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_station_location', table_name='fuel_stations')
    op.drop_index(op.f('ix_fuel_stations_city'), table_name='fuel_stations')
    op.drop_index(op.f('ix_fuel_stations_brand_id'), table_name='fuel_stations')
    op.drop_table('fuel_stations')
    op.drop_table('rate_limits')
    op.drop_table('profiles')
    op.drop_table('fuel_station_brands')
    op.drop_table('account_deletions')
    # ### end Alembic commands ###
